# Generated by Django 5.2 on 2025-04-15 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERIDapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderteam',
            name='description',
            field=models.TextField(default=datetime.datetime(2025, 4, 15, 10, 44, 44, 251601, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderteam',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
