# Generated by Django 4.2.20 on 2025-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERIDapp', '0004_financialreport_impactmetric_legaldocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('background_image', models.ImageField(upload_to='hero_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('details_page_content', models.TextField(blank=True)),
                ('testimonial', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='project_reports/')),
                ('key_achievements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(upload_to='vision_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
